### PR TITLE
Disable postgres

### PR DESCRIPTION
**Pull request by seslattery**

### CODE REVIEW

**Comment by chainlink** [comment]
I think this should be `enabled` to follow the convention of the rest of the services

**Comment by chainlink** [comment]
Looks good otherwise, might be good to have a quick test here as well

**Comment by chainlink** [comment]
I know the language is awkward, but feel strongly it should match the other services with `enabled` (I'm also adding one to pachd itself for enterprise server deployments)

**Comment by chainlink** [comment]
Will close  #127

**Comment by chainlink** [comment]
Looks good! Need to run `make pachyderm/values.schema.json` to update the json schema

**Review by chainlink — APPROVED** [review]

**Comment by seslattery** [comment]
closing - covered in #189

**Pull request closed without merging**
